version: "3"

services:
  loki:
    image: grafana/loki:2.7.1
    container_name: "loki"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    user: "0"
    environment:
      - TZ=${TZ}
      - LANG=${LANG}
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./etc/loki/config.yml:/etc/loki/config.yml
      - loki-volume:/loki
    ports:
      - "${LOKI_PORT}:3100"
    networks:
      - mco84wk0ssssg488cks4w8ck

  promtail:
    image: grafana/promtail:3.4.2
    container_name: "promtail"
    restart: always
    ports:
      - "7514:514/udp"  # Port syslog UDP
    volumes:
      - ./etc/promtail/promtail.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - loki
    networks:
      - mco84wk0ssssg488cks4w8ck

  grafana:
    image: grafana/grafana:10.2.3
    container_name: "grafana"
    restart: always
    user: "0"
    ports:
      - "${GRAFANA_PORT}"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - TZ=${TZ}
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - mco84wk0ssssg488cks4w8ck

networks:
  mco84wk0ssssg488cks4w8ck:
    external: true

volumes:
  loki-volume:
  grafana-storage:
  promtail-volume:
